import itertools
import asyncio
import motor.motor_asyncio

sports_terms = [
    # 一、专项竞技运动项目（新增细分项目）
    "Sepaktakraw",
    "Kabaddi",
    "Korfball",
    "Netball",
    "Lacrosse",
    "Polo",
    "Rugby League",
    "Rugby Union",
    "Australian Rules Football",
    "Gridiron",
    "Beach Volleyball",
    "Beach Soccer",
    "Indoor Soccer",
    "Roller Hockey",
    "Inline Skating",
    "Short Track Speed Skating",
    "Synchronized Skating",
    "Freestyle Skiing",
    "Alpine Skiing",
    "Cross-Country Skiing",
    "Nordic Combined",
    "Ski Jumping",
    "Biathlon",
    "Freestyle Wrestling",
    "Greco-Roman Wrestling",
    "Sumo",
    "Muay Thai",
    "Kickboxing",
    "Mixed Martial Arts (MMA)",
    "Fencing Foil",
    "Fencing Epee",
    "Fencing Sabre",
    "Target Shooting",
    "Skeet Shooting",
    "Trap Shooting",
    "Clay Pigeon Shooting",
    "Diving",
    "Synchronized Swimming",
    "Open Water Swimming",
    "Triathlon",
    "Duathlon",
    "Pentathlon",
    "Heptathlon",
    "Decathlon",
    "Modern Pentathlon",
    "Bobsleigh",
    "Luge",
    "Skeleton",
    "Paragliding",
    "Kitesurfing",
    "Windsurfing",
    "Wakeboarding",
    "Water Skiing",
    "Jet Skiing",
    "Parkour",
    "Freerunning",
    "Climbing",
    "Sport Climbing",
    "Bouldering",
    "Lead Climbing",
    "Speed Climbing",
    "Breakdancing (Breaking)",
    "Skateboarding Vert",
    "Skateboarding Street",
    "Surfing Big Wave",
    "Surfing Shortboard",
    "Surfing Longboard",
    # 二、进阶竞技动作（细分技术动作）
    "Backheel",
    "Overhead Kick",
    "Rabona",
    "Scorpion Kick",
    "Bicycle Kick Volley",
    "Chip Shot",
    "Lob",
    "Volley Shot",
    "Half-Volley",
    "Drive Shot",
    "Slice Shot",
    "Topspin Shot",
    "Drop Volley",
    "Smash Volley",
    "Backhand Volley",
    "Forehand Drive",
    "Backhand Slice",
    "Serve and Volley",
    "Jump Serve",
    "Float Serve",
    "Topspin Serve",
    "Jump Float Serve",
    "Spike",
    "Block Jump",
    "Dig",
    "Set",
    "Overhand Pass",
    "Underhand Pass",
    "Hook Shot",
    "Bank Shot",
    "Fadeaway Jump Shot",
    "Euro Step",
    "Crossover Dribble",
    "Behind-the-Back Dribble",
    "Between-the-Legs Dribble",
    "Spin Move",
    "Step Back",
    "Post Move",
    "Pick and Pop",
    "Give and Go",
    "Shootout",
    "Penalty Shootout",
    "Sudden Death Overtime",
    "Fist Pump",
    "Victory Lap",
    "Dive Save",
    "Finger Tip Save",
    "Slide Tackle",
    "Block Tackle",
    "Interception",
    "Clearance Header",
    "Crossfield Pass",
    "Through Ball",
    "Chipped Pass",
    "Long Ball Pass",
    "One-Two Pass",
    "Jab Cross",
    "Hook Uppercut",
    "Spin Punch",
    "Block Counter",
    "Takedown Slam",
    "Rear Naked Choke",
    "Armbar",
    "Triangle Choke",
    "Guillotine Choke",
    "Leg Lock",
    "Ankle Lock",
    "Knee Bar",
    "Vaulting Horse",
    "Parallel Bars",
    "Uneven Bars",
    "Horizontal Bar",
    "Balance Beam",
    "Floor Exercise",
    "Pommel Horse",
    "Still Rings",
    "Snatch Grip",
    "Clean Grip",
    "Jerk Drive",
    "Split Jerk",
    "Power Clean",
    # 三、赛事进阶术语（细分赛制/流程）
    "Play-In Tournament",
    "Wild Card Round",
    "Divisional Round",
    "Conference Finals",
    "Super Bowl",
    "World Series",
    "Stanley Cup Finals",
    "NBA Finals",
    "UEFA Champions League Final",
    "FIFA Club World Cup",
    "Intercontinental Cup",
    "Confederations Cup",
    "Gold Cup",
    "Euros",
    "Ashes Series",
    "Test Match",
    "One Day International (ODI)",
    "Twenty20 (T20)",
    "T20 World Cup",
    "Pro Bowl",
    "All-Star Game",
    "Rookie Showcase",
    "Combine",
    "Draft",
    "Free Agency",
    "Contract Extension",
    "Loan Deal",
    "Transfer Window",
    "Deadline Day",
    "Relegation Playoff",
    "Promotion Playoff",
    "Group Stage Decider",
    "Round Robin",
    "Double Elimination",
    "Single Elimination",
    "Best of Three",
    "Best of Five",
    "Best of Seven",
    "Home Advantage",
    "Away Form",
    "Win Streak",
    "Losing Streak",
    "Unbeaten Run",
    "Comeback Victory",
    "Last-Minute Winner",
    "Overtime Winner",
    "Penalty Winner",
    "Golden Goal",
    "Silver Goal",
    "Goal Difference",
    "Points Per Game (PPG)",
    "Goal Average",
    "Fair Play Points",
    "Disciplinary Points",
    "Suspension List",
    "Injury Reserve",
    "Match Report",
    "Post-Match Press Conference",
    "Pre-Match Warm-Up",
    "Half-Time Team Talk",
    "Tactical Briefing",
    "Video Assistant Referee (VAR) Review",
    "Referee Decision System (RDS)",
    "Hawk-Eye",
    "Goal Line Technology",
    # 四、器材进阶与专项装备
    "Carbon Fiber Racket",
    "Titanium Golf Club",
    "Composite Hockey Stick",
    "Graphite Tennis Racket",
    "Aluminum Baseball Bat",
    "Steel Boxing Gloves",
    "Leather Judo Gi",
    "Taekwondo Chest Guard",
    "Fencing Mask",
    "Archery Arm Guard",
    "Shooting Ear Protection",
    "Gymnastics Chalk",
    "Weightlifting Belt",
    "Cycling Helmet",
    "BMX Bike Frame",
    "Rowing Seat Pad",
    "Canoe Spray Deck",
    "Sailing Life Jacket",
    "Ski Bindings",
    "Snowboard Boots",
    "Ski Goggles",
    "Ice Hockey Helmet",
    "Ice Hockey Pads",
    "Curling Brush",
    "Volleyball Knee Pads",
    "Basketball Knee Braces",
    "Football Shin Guards",
    "Tennis Wristband",
    "Badminton Shuttlecock Feather",
    "Table Tennis Rubber Sheet",
    "Tennis String",
    "Golf Ball Marker",
    "Baseball Glove",
    "Softball Mitt",
    "Lacrosse Stick Head",
    "Polo Mallet",
    "Sepaktakraw Ball",
    "Kabaddi Jersey",
    "Beach Volleyball Sand Socks",
    "Swim Fins",
    "Diving Mask",
    "Snorkel",
    "Water Polo Cap",
    "Climbing Harness",
    "Climbing Shoes",
    "Chalk Bag",
    "Ski Poles",
    "Ice Skate Blades",
    # 五、战术与策略进阶术语
    "Possession-Based Football",
    "Direct Play",
    "Counter-Attacking Football",
    "High Press",
    "Low Block",
    "Mid-Block",
    "False Nine",
    "Inverted Winger",
    "Wide Playmaker",
    "Defensive Midfielder (DM)",
    "Attacking Midfielder (AM)",
    "Box-to-Box Midfielder",
    "Wing Back",
    "Center Half",
    "Sweeper Keeper",
    "Pressing Trap",
    "Offside Trap Setup",
    "Set Piece Routine",
    "Corner Kick Strategy",
    "Free Kick Wall Setup",
    "Penalty Taking Technique",
    "Defensive Switching",
    "Attacking Overlaps",
    "Underlapping Runs",
    "Cutback Pass",
    "Cross into the Box",
    "Shoot on Sight",
    "Hold Up Play",
    "Link-Up Play",
    "Build-Up Play",
    "Transition Play",
    "Fast Break Offense",
    "Half-Court Trap",
    "Zone Blitz",
    "Man Coverage",
    "Zone Coverage",
    "Blitz Package",
    "Screen Play",
    "Pick and Roll Variation",
    "Give and Go Combination",
    "Triangle Offense",
    "Princeton Offense",
    "Motion Offense",
    "Zone Defense Rotation",
    "Help Side Defense",
    "Double Team",
    "Triple Team",
    "Full-Court Press Defense",
]


async def get_async_ny_mongo_link(db_name: str, coll_name: str):
    mongo_uri = "mongodb://developer:QYZ3mxps4POMFb76@mongo-wy-hk.mereith.top:30017/?authSource=admin"
    mongo_client = motor.motor_asyncio.AsyncIOMotorClient(
        mongo_uri,
        maxPoolSize=200,
        minPoolSize=10,
        maxIdleTimeMS=60000,
    )
    await mongo_client.admin.command("ping")
    collection = mongo_client[db_name][coll_name]
    return collection


async def main():
    keyword_with_page_total_77_coll = await get_async_ny_mongo_link(
        "youtube_task_favortrain", "keyword_with_page_total_77"
    )
    await keyword_with_page_total_77_coll.create_index("keyword", unique=True)
    for batched_tuple in itertools.batched(sports_terms, 10000):
        try:
            await keyword_with_page_total_77_coll.insert_many(
                [{"keyword": keyword} for keyword in batched_tuple], ordered=False
            )
        except Exception as e:
            print(e.__class__.__name__)


async def main2():
    keyword_with_page_total_77_coll = await get_async_ny_mongo_link(
        "youtube_task_favortrain", "keyword_with_page_total_77"
    )
    filmont_url_77_coll = await get_async_ny_mongo_link(
        "youtube_task_favortrain", "filmont_url_77"
    )
    task_list = []
    async for mongo_info in keyword_with_page_total_77_coll.find(
        {"crawler_status": None}
    ):
        for i in range(
            1,
            (
                83
                if int(mongo_info["page_total"]) >= 82
                else int(mongo_info["page_total"])
            ),
        ):
            task_list.append(
                {
                    "keyword": mongo_info["keyword"],
                    "page_index": i,
                    "crawler_status": None,
                }
            )

    for batched_tuple in itertools.batched(task_list, 10000):
        await filmont_url_77_coll.insert_many(list(batched_tuple), ordered=False)
        print("完成一批")


if __name__ == "__main__":
    asyncio.run(main2())
